### ISSUE TITLE
A factor is missing in dyc equation 

### ISSUE THREAD

**Issue by manu9418** [mkoohafkan/rivr#6]
Hi Michael, I think these lines https://github.com/mkoohafkan/rivr/blob/master/src/rivmech_characteristic_v7.cpp#L169-L171 must be:
```
   dy = (pow(gp["A"], 3.0)/gp["dAdy"] - pow(Q, 2.0)/g) / 
     ( (3.0*pow(gp["A"], 2.0) - pow(gp["A"], 3.0)*gp["dTdy"] / 
      pow(gp["dAdy"], 2.0))*(2*pow(A,3/2)*pow(dAdy,-0.5) ) );
```
if we consider two equations that you mention in technical_vignette.Rmd
```
f(yc) =  dE/dy = 0 = 1 - (Q**2/(g*A**3))*(dA/dy)
df(yc) = (3/2)*((A*T)**(0.5))-(1/2)*((A/T)**(3/2))*(dT/dy)
```
I hope I'm wrong but just in case it would be a good idea to review it.
Thank you for sharing.
Take care.

**Comment by mkoohafkan** [comment]
Can you provide more information? It seems like you are concerned that the equation for critical depth is not correct. I tested it against [the three channel setups in example 5.4 of this text](https://web.itu.edu.tr/~bulu/hydraulics_files/lecture_notes_05.pdf#page=8) and the critical depths match. Do you have a working example that shows the critical depth calculation is incorrect?

**Comment by mkoohafkan** [comment]
This question revolves around the definition of the `dy` term in the Newton-Raphson formulation for solving critical depth.

This function represents the `dy` formulation in the current code base:

```cpp
dy_code = function(y, Q, B, SS, g = 9.81) {
  gp = channel_geom(y, B, SS)
(pow(gp["A"], 3.0)/gp["dAdy"] - pow(Q, 2.0)/g) / 
    (3.0*pow(gp["A"], 2.0) - pow(gp["A"], 3.0)*gp["dTdy"] / 
    pow(gp["dAdy"], 2.0))
}
```

The documentation describes a different formulation:

```cpp
dy_doc = function(y, Q, B, SS, g = 9.81) {
  gp = channel_geom(y, B, SS)
  (1 - pow(Q, 2.0)*gp["dAdy"]/(g*pow(gp["A"], 3.0))) / 
    (1.5*sqrt(gp["A"]*gp["dAdy"]) - 0.5*pow(gp["A"]/gp["dAdy"], 1.5)*gp["dTdy"])    
}
```

Both formulations approach zero as the correct critical depth is found. The plot below shows how the two formulations compare for solving [the three channel setups in example 5.4](https://web.itu.edu.tr/~bulu/hydraulics_files/lecture_notes_05.pdf#page=8), as you can see they intersect and evaluate to zero at the critical depth.

![image](https://user-images.githubusercontent.com/4790348/144148635-ef85ebd4-0fcc-42f4-9a2f-a5cfc5f959c8.png)

Not sure why I used the alternate formulation in the code but the results are correct. I may update the code to use the same equation as the documentation in the future.
